config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :orders
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#home', as: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    
    has_many :orders
    has_many :tasks, through: :orders
    
    
    validates_presence_of :first_name, :last_name, :phone, :address
    validates_format_of :phone, with: /\d{8}/, message: "should be 8 digits"
    
    scope :alphabetical, -> { order('name') }
    
    def name
         "#{first_name}, #{last_name}"
    end
    
    def current_order
        curr_order = self.orders.select{|a| a.due_date.nil?}
        return nil if curr_order.empty?
        curr_order.first   # return as a single object, not an array
    end
    
    

end

app/models/order.rb
class Order < ApplicationRecord
    
    belongs_to :clients
    belongs_to :tasks
    
    validates_date :date_of_order, on_or_before: lambda { Date.current }, on_or_before_message: "cannot be in the future"
    validates_date :due_date, after: :date_of_order, on_or_before: lambda { Date.current }, allow_blank: true
    validates_presence_of :client_id, on: :update
    validates_presence_of :task_id, on: :update
    validates_presence_of :total_price
    
    scope :current,       -> { where(due_date: nil) }
    scope :past,          -> { where.not(due_date: nil) }
    scope :chronological, -> { order('date_of_order DESC, due_date DESC') }
    scope :by_client,   -> { joins(:client).order('first_name, last_name') }
    scope :by_task,      -> { joins(:task).order('name') }
    
    
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :phone, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:client_id, :task_id, :date_of_order, :due_date, :total_price)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :cleaning_type, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="input-field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="input-field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="input-field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

 <div class="actions">
    <%= form.submit :class=>"btn waves-effect waves-light" %>
    <%= link_to 'Cancel', clients_path, :class => 'waves-effect waves-light btn red' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.phone %></td>
        <td><%= client.address %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/home.html.erb
	<div class= "center">

		
		<div id= "about"></div>
		<di id="about-us"><h1>WELCOME TO</h1>
		 The Laundry Service<br />
		 <a href="#" role="button" class="btn btn-info btn-lg" id="btn">About Us</a>
		 <a href="#" role="button" class="btn btn-info btn-lg" id="btn">Contact Us</a>
		 </div>
		 
		<img src="/assets/laundry.jpg" id = "about_image" width= 100% height= 800px >

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Laundry</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Dropdown Structure -->
<nav class="navbar-inner">  
    
    <a href="/" id="brand-logo">The Laundry Service</a>
    <img src="/assets/laundry_icon.jpg" id = "icon" width= 50px height= 70px >
    <ul class="right">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="/stores" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Orders
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href= "/orders"> Order List</a>
          <a class="dropdown-item" href="/orders/new">New Order</a>
          <a class="dropdown-item" href= "/active"> Active Store List</a>
          <a class="dropdown-item" href="/inactive">Inactive Store List</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="/employees" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tasks
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href= "/tasks"> Tasks List</a>
          <a class="dropdown-item" href="/tasks/new">New Task</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="/employees" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Clients
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href= "/clients"> Clients List</a>
          <a class="dropdown-item" href="/clients/new">Add New Client</a>
        </div>
      </li>
    </ul>

</nav>

    <div class="center">
      <!-- MAIN CONTENT GOES HERE -->
      <%= yield %> 
    </div>


  </div>
  <footer>

    
  </footer> 
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
<%= javascript_include_tag "application" %>
<% flash.each do |message_type, message| %>
  <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
<% end %>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field">
    <%= form.label :client_id %>
    <%= form.number_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.number_field :task_id %>
  </div>

  <div class="field">
    <%= form.label :date_of_order %>
    <%= form.text_field :date_of_order, prompt: "Date of Order", class: "datepicker", :value =>
					(form.object.date_of_order.strftime('%B %d, %Y') if form.object.date_of_order != nil)%>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.text_field :due_date, prompt: "Due Date", class: "datepicker", :value =>
					(form.object.due_date.strftime('%B %d, %Y') if form.object.due_date != nil)%>
  </div>

  <div class="field">
    <%= form.label :total_price %>
    <%= form.number_field :total_price %>
  </div>

 <div class="actions">
    <%= form.submit :class => "btn btn-outline-secondary" %>
    <%= link_to 'Cancel', orders_path, :class => "btn btn-outline-secondary" %>
  </div>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Task</th>
      <th>Date of order</th>
      <th>Due date</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.client_id %></td>
        <td><%= order.task_id %></td>
        <td><%= order.date_of_order %></td>
        <td><%= order.due_date %></td>
        <td><%= order.total_price %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @order.client_id %>
</p>

<p>
  <strong>Task:</strong>
  <%= @order.task_id %>
</p>

<p>
  <strong>Date of order:</strong>
  <%= @order.date_of_order %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @order.due_date %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cleaning_type %>
    <%= form.text_field :cleaning_type %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost %>
  </div>

 <div class="actions">
    <%= form.submit :class => "btn btn-outline-secondary" %>
    <%= link_to 'Cancel', orders_path, :class => "btn btn-outline-secondary" %>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>Tasks</h1>
<%= link_to 'New Task', new_task_path, :class=> "right"%>
<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Cleaning type</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.cleaning_type %></td>
        <td><%= task.cost %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Cleaning type:</strong>
  <%= @task.cleaning_type %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @task.cost %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>